[package]
name = "reform"
version = "0.1.0"
readme = "README.md"
authors = ["Ben Ruijl <benruyl@gmail.com>"]

[features]
profile = ["cpuprofiler"]

[dependencies]
itertools = "^0.5.8"
clap = "^2.26.0"
log = "0.3.8"
env_logger = "0.4.3"
rand = "0.3.16"
combine = "2.5.1"
byteorder = "1"
cpuprofiler = { version = "0.0.3", optional = true }
